version: "3.3"
services:
  adservice:
    build: adservice
    image: ad-image
    container_name: adservice
    ports:
      - 9555:9555
    restart: always
    networks: 
      - net
    
  emailservice:
    build: emailservice
    image: email-image
    container_name: emailservice
    ports:
      - 5000:8080
    restart: always
    networks: 
      - net
  checkoutservice:
    build: checkoutservice
    image: checkout
    container_name: checkoutservice
    ports: 
      - 5050:5050
    restart: always
    networks: 
      - net
    environment:
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      PAYMENT_SERVICE_ADDR: paymentservice:50051
      EMAIL_SERVICE_ADDR: emailservice:5000
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
    depends_on: 
      - productcatalogservice
      - shippingservice
      - paymentservice
      - emailservice
      - currencyservice
      - cartservice
  recommendationservice: 
    build: recommendationservice
    image: recommendationservice
    container_name: recommendationservice
    ports: 
      - 8080:8080
    restart: always
    networks: 
      - net
    depends_on: 
      - productcatalogservice
    environment: 
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
  frontend:
    build: frontend
    image: frontend
    container_name: frontend
    ports:
      - 80:8080
    restart: always
    networks: 
      - net
    depends_on: 
      - productcatalogservice
      - shippingservice
      - currencyservice
      - cartservice
      - recommendationservice
      - checkoutservice
      - adservice
    environment: 
      PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
      SHIPPING_SERVICE_ADDR: shippingservice:50051
      CURRENCY_SERVICE_ADDR: currencyservice:7000
      CART_SERVICE_ADDR: cartservice:7070
      RECOMMENDATION_SERVICE_ADDR: recommendationservice:8080
      CHECKOUT_SERVICE_ADDR: checkoutservice:5050
      AD_SERVICE_ADDR: adservice:9555
  paymentservice:
    build: paymentservice
    image: paymentservice
    container_name: paymentservice
    ports:
      - 50051:50051
    restart: always
    networks: 
      - net
  productcatalogservice:
    build: productcatalogservice
    image: productcatalogservice
    container_name: productcatalogservice 
    ports:
      - 3550:3550
    restart: always
    networks: 
      - net
  cartservice:
    build: cartservice/src
    image: cartservice
    container_name: cartservice
    ports: 
      - 7070:7070
    depends_on:
      - redis-cart
    environment: 
      REDIS_ADDR: redis-cart:6379
    restart: always
    networks: 
      - net
  currencyservice:
    build: currencyservice
    image: currencyservice
    container_name: currencyservice
    ports: 
      - 7000:7000
    restart: always
    networks: 
      - net
  shippingservice:
    build: shippingservice
    image: shippingservice
    container_name: shippingservice
    ports: 
      - 50051:50051
    restart: always
    networks: 
      - net
  redis-cart:
    image: redis:alpine
    container_name: redis-cart
    ports:
      - 6379:6379
    restart: always
    networks: 
      - net
networks: 
  net:
      